apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress
  namespace: demo2
spec:
  ingressClassName: nginx
  rules:
  - host: dev.example.com
    http:
      paths:
      - path: /recepcion
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port:
              number: 80
      - path: /autentica
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 80
