apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: demo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: goldmandock/demoapp01
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: demo3
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: coffee
