apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress
  namespace: demo3
spec:
  ingressClassName: nginx
  rules:
  - host: qa.example.com
    http:
      paths:
      - path: /test1
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port:
              number: 8080
      - path: /test2
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 8080
