apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpleapp-ingress
  namespace: demo3
spec:
  ingressClassName: nginx
  rules:
  - host: simpleapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simpleapp-svc1
            port:
              number: 80      
