apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpleapp-ingress
  namespace: democd
spec:
  ingressClassName: nginx
  rules:
  - host: simpleapp.example.com
    http:
      paths:
      - path: /serviceA
        pathType: Prefix
        backend:
          service:
            name: simpleapp-svc
            port:
              number: 80      
