apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simpleapp-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simpleapp-deploy
  minReplicas: 25
  maxReplicas: 30
  targetCPUUtilizationPercentage: 80
