apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appmac-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appmac-deploy
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
