---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-deploy
  namespace: demo3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: simpleapp 
  template:
    metadata:
      labels:
        app: simpleapp 
    spec:
      containers:
      - name: simpleapp 
        image: goldmandock/simpleapp:latest
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-svc
  namespace: demo3
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: simpleapp
