---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmac-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appmac 
  template:
    metadata:
      labels:
        app: appmac 
    spec:
      containers:
      - name:  appmac
        image: goldmandock/appmac:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "350m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20           
        ports:
        - containerPort: 80
      hostAliases:
      - ip: 8.8.8.8
        hostnames:
        - google.com
        
---
apiVersion: v1
kind: Service
metadata:
  name: appmac-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: appmac
